// <auto-generated />
using System;
using HRL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRL.Migrations
{
    [DbContext(typeof(HRLContext))]
    [Migration("20230713162327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRL.Database.DatenAnSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllgemeinStoerungQuittieren")
                        .HasColumnType("bit");

                    b.Property<bool>("AllgemeinWatchDog")
                        .HasColumnType("bit");

                    b.Property<int>("Auftraege0Art")
                        .HasColumnType("int");

                    b.Property<double>("Auftraege0Gewicht")
                        .HasColumnType("float");

                    b.Property<int>("Auftraege0LagerId")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionXP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionYP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionZP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DatenAnSps");
                });

            modelBuilder.Entity("HRL.Database.DatenAnSpsHistorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllgemeinStoerungQuittieren")
                        .HasColumnType("bit");

                    b.Property<bool>("AllgemeinWatchDog")
                        .HasColumnType("bit");

                    b.Property<int>("Auftraege0Art")
                        .HasColumnType("int");

                    b.Property<double>("Auftraege0Gewicht")
                        .HasColumnType("float");

                    b.Property<int>("Auftraege0LagerId")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionXP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionYP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionZP")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZeitStempel")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DatenAnSpsHistorie");
                });
#pragma warning restore 612, 618
        }
    }
}
