// <auto-generated />
using System;
using HRL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRL.Migrations
{
    [DbContext(typeof(HRLContext))]
    partial class HRLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRL.Database.AllgemeinAnSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("StoerungQuittieren")
                        .HasColumnType("bit");

                    b.Property<bool>("WatchDog")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AllgemeinesAnSps");
                });

            modelBuilder.Entity("HRL.Database.AllgemeinVonSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Kommunikation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AllgemeinesVonSps");
                });

            modelBuilder.Entity("HRL.Database.AuftragAnSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Art")
                        .HasColumnType("smallint");

                    b.Property<float>("Gewicht")
                        .HasColumnType("real");

                    b.Property<short>("LagerId")
                        .HasColumnType("smallint");

                    b.Property<short>("PositionXP")
                        .HasColumnType("smallint");

                    b.Property<short>("PositionYP")
                        .HasColumnType("smallint");

                    b.Property<short>("PositionZP")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("AuftraegeAnSps");
                });

            modelBuilder.Entity("HRL.Database.AuftragAnSpsHistorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Auftraege0Art")
                        .HasColumnType("int");

                    b.Property<double>("Auftraege0Gewicht")
                        .HasColumnType("float");

                    b.Property<int>("Auftraege0LagerId")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionXP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionYP")
                        .HasColumnType("int");

                    b.Property<int>("Auftraege0PositionZP")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZeitStempel")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuftraegeAnSpsHistorie");
                });

            modelBuilder.Entity("HRL.Database.FehlerlisteVonSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumUhrzeit")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FehlerlistenVonSps");
                });

            modelBuilder.Entity("HRL.Database.TransportmaschineVonSps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BelegungPhysisch")
                        .HasColumnType("bit");

                    b.Property<float>("IstPositionX")
                        .HasColumnType("real");

                    b.Property<int>("IstPositionXP")
                        .HasColumnType("int");

                    b.Property<float>("IstPositionY")
                        .HasColumnType("real");

                    b.Property<int>("IstPositionYP")
                        .HasColumnType("int");

                    b.Property<float>("IstPositionZ")
                        .HasColumnType("real");

                    b.Property<int>("IstPositionZP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SollPositionX")
                        .HasColumnType("real");

                    b.Property<int>("SollPositionXP")
                        .HasColumnType("int");

                    b.Property<float>("SollPositionY")
                        .HasColumnType("real");

                    b.Property<int>("SollPositionYP")
                        .HasColumnType("int");

                    b.Property<float>("SollPositionZ")
                        .HasColumnType("real");

                    b.Property<int>("SollPositionZP")
                        .HasColumnType("int");

                    b.Property<int>("Zustand")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportmaschinenVonSps");
                });
#pragma warning restore 612, 618
        }
    }
}
